#!/usr/bin/env python3
"""Patch notebook 4, cell 11: expand fig6 from 1×3 (CF only) to 2×3
(top row = actual simulation covariances, bottom row = CF predictions)."""
import json, pathlib

NB = pathlib.Path(__file__).resolve().parent.parent / "notebooks" / "4. roughness_scale-cf-channel_eqs.ipynb"
nb = json.loads(NB.read_text())
cells = nb["cells"]

# Find the cell containing the 1×3 CF plot (fig6)
target_ci = None
for ci, cell in enumerate(cells):
    if cell["cell_type"] != "code":
        continue
    src = "".join(cell["source"])
    if ("er_T0_CF" in src and "er_T2_CF" in src and "er_lead_CF" in src
            and "fig2, axes2" in src and "fig6_pred_vs_obs_CF" in src):
        target_ci = ci
        break

if target_ci is None:
    print("ERROR: could not find fig6 cell"); exit(1)

print(f"Found fig6 cell at index {target_ci}")

# Build the new cell source line by line
L = []
a = L.append

a("# ── Predicted vs observed effect ratio — CF perturbation expansions ────────────\n")
a("# Two rows: top = actual (simulation) covariances, bottom = CF predictions.\n")
a("# Markers are coloured by the variable that explains the most variance in the\n")
a("# Leading-term (CF) residuals (pred − obs).\n")
a("\n")
a("from stats import rmse as _rmse, r2 as _r2, best_residual_correlate\n")
a("\n")
a("# ── observed column ─────────────────────────────────────────────────────────────\n")
a("er_obs_col = 'effect_ratio'\n")
a("\n")
a("# ── compute CF-based equivalent roughness predictions ──────────────────────────\n")
a("# Leading term: direct back-calculation from CF-averaged h, U\n")
a("summary['er_lead_CF'] = (\n")
a("    summary['<h>_CF']**(2/3) * summary['So']**0.5\n")
a("    / (summary['<U>_CF'] * summary['<n>'])\n")
a(")\n")
a("\n")
a("# T₀ and T₂ using EXACT CF moments (no linearisation)\n")
a("# Under CF: U_i ∝ n_i^{-3/5}, h_i ∝ n_i^{3/5}\n")
a("# So (1+υ) = (1+r)^{-3/5} and (1+η) = (1+r)^{3/5} exactly.\n")
a("_nbar  = summary['<n>']\n")
a("_rv    = (summary['alpha_v'] - _nbar) / _nbar   # r for veg cells\n")
a("_rb    = (summary['alpha_b'] - _nbar) / _nbar   # r for bare cells\n")
a("_fV    = summary['fV']\n")
a("\n")
a("# exact CF fluctuations (not linearised)\n")
a("_uv_v  = (1 + _rv)**(-3/5) - 1    # υ for veg cells\n")
a("_uv_b  = (1 + _rb)**(-3/5) - 1    # υ for bare cells\n")
a("_eta_v = (1 + _rv)**(3/5)  - 1    # η for veg cells\n")
a("_eta_b = (1 + _rb)**(3/5)  - 1    # η for bare cells\n")
a("\n")
a("# six second moments (binary-weighted)\n")
a("_r2_cf      = _fV * _rv**2       + (1-_fV) * _rb**2\n")
a("_ups2_cf    = _fV * _uv_v**2     + (1-_fV) * _uv_b**2\n")
a("_r_ups_cf   = _fV * _rv*_uv_v    + (1-_fV) * _rb*_uv_b\n")
a("_r_eta_cf   = _fV * _rv*_eta_v   + (1-_fV) * _rb*_eta_b\n")
a("_eta_ups_cf = _fV * _eta_v*_uv_v + (1-_fV) * _eta_b*_uv_b\n")
a("_eta2_cf    = _fV * _eta_v**2    + (1-_fV) * _eta_b**2\n")
a("\n")
a("# T₀: r, υ terms only\n")
a("summary['er_T0_CF'] = 1 + _r2_cf + _ups2_cf + 4*_r_ups_cf\n")
a("\n")
a("# Full 2nd-order: all six terms\n")
a("summary['er_T2_CF'] = (\n")
a("    summary['er_T0_CF']\n")
a("    - (8/3) * _r_eta_cf\n")
a("    - (8/3) * _eta_ups_cf\n")
a("    + (14/9) * _eta2_cf\n")
a(")\n")
a("\n")
a("# ── slope-integrated leading term ───────────────────────────────────────────────\n")
a("summary['er_lead_int'] = (\n")
a("    summary['<ha>']**(2/3) * summary['So']**0.5\n")
a("    / (summary['<Ua>'] * summary['<n>'])\n")
a(")\n")
a("\n")
a("# ── actual (simulation) covariances: T₀ and T₂ ────────────────────────────────\n")
a("summary['er_T0_actual'] = (\n")
a("    1\n")
a("    + summary['<r2>']\n")
a("    + summary['<ups2>']\n")
a("    + 4 * summary['<r ups>']\n")
a(")\n")
a("summary['er_T2_actual'] = (\n")
a("    1\n")
a("    + summary['<r2>']\n")
a("    + summary['<ups2>']\n")
a("    + 4 * summary['<r ups>']\n")
a("    - (8/3) * summary['<r eta>']\n")
a("    - (8/3) * summary['<eta ups>']\n")
a("    + (14/9) * summary['<eta2>']\n")
a(")\n")
a("\n")
a("# ── method lists for each row ────────────────────────────────────────────────────\n")
a("methods = [\n")
a("    ('er_lead_CF',   'Leading term (CF)'),\n")
a("    ('er_T0_CF',     r'$T_0$: $r, \\upsilon$ terms (CF)'),\n")
a("    ('er_T2_CF',     r'Full 2nd-order (CF)'),\n")
a("]\n")
a("methods_actual = [\n")
a("    ('er_lead_int',   'Leading term (slope-integrated)'),\n")
a("    ('er_T0_actual',  r'$T_0$: actual covariances'),\n")
a("    ('er_T2_actual',  r'Full 2nd-order: actual covariances'),\n")
a("]\n")
a("\n")
a("# ── find variable that best explains Leading-term residuals ─────────────────────\n")
a("_obs_arr    = summary[er_obs_col].to_numpy(float)\n")
a("_lead_pred  = summary['er_lead_CF'].to_numpy(float)\n")
a("_m_lead     = np.isfinite(_obs_arr) & np.isfinite(_lead_pred)\n")
a("_lead_resid = _lead_pred[_m_lead] - _obs_arr[_m_lead]\n")
a("\n")
a("_candidates = best_residual_correlate(\n")
a("    summary, _lead_resid, mask=_m_lead,\n")
a("    sim_cols=['fV', 'sigma', 'p', 'tr', 'l', 'aniso'],\n")
a(")\n")
a("COLOR_BY_VAR_4P   = _candidates[0][0] if _candidates else 'fV'\n")
a("_pretty           = {'fV': r'$f_V$', 'sigma': r'$\\sigma$', 'aniso': 'anisotropy',\n")
a("                     'p': r'$p$ (mm/h)', 'tr': r'$t_r$ (min)', 'l': r'$L$ (m)'}\n")
a("COLOR_BY_LABEL_4P = _pretty.get(COLOR_BY_VAR_4P, COLOR_BY_VAR_4P)\n")
a("_cmap_name_4p     = VAR_CMAPS.get(COLOR_BY_VAR_4P, 'viridis')\n")
a("_cmap_4p_base     = plt.get_cmap(_cmap_name_4p)\n")
a("_cmap_4p          = mpl.colors.LinearSegmentedColormap.from_list(\n")
a("    f'trunc_{_cmap_name_4p}', _cmap_4p_base(np.linspace(0.2, 0.95, 256)))\n")
a("\n")
a("if _candidates:\n")
a("    print(f\"Coloring by: {COLOR_BY_VAR_4P}  (|r| with leading-term residual = {abs(_candidates[0][1]):.3f})\")\n")
a("    print(\"Top correlates:\", [(c, round(r, 3)) for c, r in _candidates[:4]])\n")
a("else:\n")
a("    print(f\"Coloring by: {COLOR_BY_VAR_4P}  (no valid correlates found; using default)\")\n")
a("\n")
a("# ── build discrete colour levels ────────────────────────────────────────────────\n")
a("_color_vals_raw = pd.to_numeric(summary[COLOR_BY_VAR_4P], errors='coerce')\n")
a("_unique_vals    = sorted(_color_vals_raw.dropna().unique())\n")
a("MAX_LEVELS_4P   = 6\n")
a("if len(_unique_vals) > MAX_LEVELS_4P:\n")
a("    _binned      = pd.qcut(_color_vals_raw, q=MAX_LEVELS_4P, duplicates='drop')\n")
a("    _bin_levels  = _binned.cat.categories.tolist()\n")
a("    _color_vals  = _binned.cat.codes.astype(float)\n")
a("    _color_vals[_binned.isna()] = np.nan\n")
a("    _color_levels = list(range(len(_bin_levels)))\n")
a("    _level_label  = lambda i: f'[{_bin_levels[i].left:.3g}, {_bin_levels[i].right:.3g}]'\n")
a("else:\n")
a("    _color_vals   = _color_vals_raw.to_numpy(float)\n")
a("    _color_levels = _unique_vals\n")
a("    _level_label  = lambda v: f'{v}'\n")
a("\n")
a("_norm_4p    = mpl.colors.Normalize(vmin=min(_color_levels), vmax=max(_color_levels))\n")
a("_palette_4p = {cv: _cmap_4p(_norm_4p(cv)) for cv in _color_levels}\n")
a("\n")
a("# ── 2×3 plot ────────────────────────────────────────────────────────────────────\n")
a("from matplotlib.ticker import MaxNLocator\n")
a("from matplotlib.lines import Line2D\n")
a("\n")
a("fs_lab, fs_tck, fs_leg = 13, 12, 11\n")
a("_all_row_methods = [methods_actual, methods]\n")
a("_row_labels = ['Simulation fields', 'CF approximation']\n")
a("\n")
a("fig2, axes2 = plt.subplots(2, 3, figsize=(15, 9), sharey='row')\n")
a("fig2._method_metrics = {}\n")
a("\n")
a("for row_idx, (_row_methods, _row_label) in enumerate(zip(_all_row_methods, _row_labels)):\n")
a("    for col_idx, (pred_col, title) in enumerate(_row_methods):\n")
a("        ax = axes2[row_idx, col_idx]\n")
a("        obs  = summary[er_obs_col].to_numpy(float)\n")
a("        pred = (summary[pred_col].to_numpy(float)\n")
a("                if pred_col in summary.columns else np.full(len(summary), np.nan))\n")
a("\n")
a("        finite = np.isfinite(obs) & np.isfinite(pred)\n")
a("        if finite.sum() == 0:\n")
a("            ax.set_title(f\"{title}\\n(no data)\", fontsize=fs_lab)\n")
a("            continue\n")
a("\n")
a("        lo = min(np.nanmin(obs[finite]), np.nanmin(pred[finite]))\n")
a("        hi = max(np.nanmax(obs[finite]), np.nanmax(pred[finite]))\n")
a("        ax.plot([lo, hi], [lo, hi], 'k-', lw=1, zorder=0)\n")
a("\n")
a("        _rng = np.random.default_rng(42)\n")
a("        for cv in _color_levels:\n")
a("            sel = finite & (np.abs(_color_vals - cv) < 1e-9)\n")
a("            if sel.sum() == 0:\n")
a("                continue\n")
a("            _jitter = _rng.normal(0, 0.005, sel.sum())\n")
a("            ax.scatter(obs[sel], pred[sel] + _jitter,\n")
a("                       color=_palette_4p[cv], marker='o',\n")
a("                       s=25, alpha=0.80, edgecolors='none', zorder=3)\n")
a("\n")
a("        rmse = _rmse(pred[finite], obs[finite])\n")
a("        r2v  = _r2(pred[finite], obs[finite])\n")
a("        ax.set_title(title, fontsize=fs_lab - 1)\n")
a("        ax.text(0.97, 0.05, f'RMSE={rmse:.3f}\\n$R^2$={r2v:.2f}',\n")
a("                transform=ax.transAxes, fontsize=fs_tck - 1,\n")
a("                ha='right', va='bottom', zorder=5)\n")
a("        ax.tick_params(labelsize=fs_tck)\n")
a("        ax.grid(True, alpha=0.2)\n")
a("        ax.xaxis.set_major_locator(MaxNLocator(nbins=4))\n")
a("        ax.yaxis.set_major_locator(MaxNLocator(nbins=4))\n")
a("\n")
a("        if row_idx == 1:\n")
a("            ax.set_xlabel(r\"observed $n_e/\\langle n\\rangle$\", fontsize=fs_lab)\n")
a("        if col_idx == 0:\n")
a("            ax.set_ylabel(f\"{_row_label}\\n\" + r\"predicted $n_e/\\langle n\\rangle$\",\n")
a("                          fontsize=fs_lab)\n")
a("\n")
a("        fig2._method_metrics[pred_col] = dict(title=title, rmse=rmse, r2=r2v)\n")
a("\n")
a("fig2.suptitle(r\"Predicted vs observed $n_e/\\langle n\\rangle$\"\n")
a("              f\"  —  coloured by {COLOR_BY_LABEL_4P}\", fontsize=fs_lab + 1)\n")
a("fig2.tight_layout(rect=[0, 0, 0.84, 1])\n")
a("\n")
a("# ── legend ───────────────────────────────────────────────────────────────────────\n")
a("leg_ax = fig2.add_axes([0.85, 0.12, 0.13, 0.74])\n")
a("leg_ax.set_axis_off()\n")
a("_leg_handles = [Line2D([0], [0], marker='o', color='w',\n")
a("                       markerfacecolor=_palette_4p[cv], markersize=8, label=_level_label(cv))\n")
a("                for cv in _color_levels]\n")
a("leg_ax.legend(handles=_leg_handles, title=COLOR_BY_LABEL_4P, loc='center left',\n")
a("              fontsize=fs_leg, title_fontsize=fs_leg, frameon=True, handlelength=1.2)\n")
a("\n")
a("# ── save figure ──────────────────────────────────────────────────────────────────\n")
a("_fig_dir, _, _ = _fig_dirs()\n")
a("_fig6_name = 'fig6_pred_vs_obs_CF.png'\n")
a("fig2.savefig(_os.path.join(_fig_dir, _fig6_name), dpi=300, bbox_inches='tight')\n")
a("\n")
a("# ── build dynamic registry text from per-method metrics ──────────────────────\n")
a("_mm = fig2._method_metrics\n")
a("_interp_lines = []\n")
a("for _row_methods in _all_row_methods:\n")
a("    for _pc, _ttl in _row_methods:\n")
a("        _m = _mm.get(_pc, {})\n")
a("        _r2s = f\"R\\u00b2={_m['r2']:.2f}\" if np.isfinite(_m.get('r2', np.nan)) else \"R\\u00b2 undefined\"\n")
a("        _rms = f\"RMSE={_m['rmse']:.3f}\" if np.isfinite(_m.get('rmse', np.nan)) else \"\"\n")
a("        _interp_lines.append(f\"  - {_m.get('title', _pc)}: {_r2s}, {_rms}\".rstrip(', '))\n")
a("\n")
a("# Identify best method by R² (excluding NaN)\n")
a("_valid = [(k, v) for k, v in _mm.items() if np.isfinite(v.get('r2', np.nan))]\n")
a("if _valid:\n")
a("    _best_key  = max(_valid, key=lambda x: x[1]['r2'])\n")
a("    _worst_key = min(_valid, key=lambda x: x[1]['r2'])\n")
a("    _best_title,  _best_r2  = _best_key[1]['title'],  _best_key[1]['r2']\n")
a("    _worst_title, _worst_r2 = _worst_key[1]['title'], _worst_key[1]['r2']\n")
a("    _concise_6 = (f\"Predicted vs observed n_e/<n> for six predictions \"\n")
a("                  f\"(3 actual-covariance + 3 CF-based), coloured by {COLOR_BY_VAR_4P}. \"\n")
a("                  f\"{_best_title} performs best (R\\u00b2={_best_r2:.2f}); \"\n")
a("                  f\"{_worst_title} is weakest (R\\u00b2={_worst_r2:.2f}).\")\n")
a("else:\n")
a("    _concise_6 = f\"Predicted vs observed n_e/<n> for six predictions, coloured by {COLOR_BY_VAR_4P}.\"\n")
a("\n")
a("update_figure_registry(\n")
a("    'fig6', _fig6_name,\n")
a("    'Predicted vs observed n_e/<n> — 2x3 grid.\\n'\n")
a("    'Top row: simulation-derived fields (slope-integrated leading term, T0 actual, full 2nd-order actual).\\n'\n")
a("    'Bottom row: CF approximation (leading term, T0 exact CF, full 2nd-order exact CF).\\n'\n")
a("    f'Markers coloured by {COLOR_BY_VAR_4P} (highest |r| with leading-term residual).\\n'\n")
a("    'RMSE/R² annotated per panel.\\n'\n")
a("    '\\n'\n")
a("    'Per-method performance:\\n' + '\\n'.join(_interp_lines) + '\\n'\n")
a("    '\\n'\n")
a("    f'Residuals correlate most with {COLOR_BY_VAR_4P}; '\n")
a("    f'dominant errors occur at extreme {COLOR_BY_VAR_4P} values.',\n")
a("    concise=_concise_6)\n")
a("\n")
a("plt.show()\n")

cells[target_ci]["source"] = L
NB.write_text(json.dumps(nb, indent=1, ensure_ascii=False) + "\n")
print(f"Replaced cell {target_ci} with 2×3 grid version. Done.")
