"""Fix cell 12 (length-scale attribution) in decomp notebook."""
import json

NB = "/Users/octaviacrompton/Projects/roughness-scale/notebooks/3. roughness_scale-decomp.ipynb"

with open(NB) as f:
    nb = json.load(f)

# Find the cell we just inserted (contains "Length-scale attribution of S_f")
target_idx = None
for i, c in enumerate(nb["cells"]):
    src = "".join(c["source"])
    if "Length-scale attribution of S_f" in src and c["cell_type"] == "code":
        target_idx = i
        break
assert target_idx is not None, "Could not find the attribution code cell!"
print(f"Found attribution code cell at index {target_idx}")

# Build the correct source as a list of lines
L = []
a = L.append

a("# " + "=" * 76)
a("# Length-scale attribution of S_f decomposition terms")
a("# " + "=" * 76)
a("from matplotlib.lines import Line2D")
a("")
a("# -- Reuse same subset and term definitions as fig 3 --")
a('_sub = summary.query("hydro_err < 0.05 and p == 8 and tr == 60 and aniso > 1").copy()')
a("")
a("_coefs   = [1, 1, 4, -8/3, -8/3, 14/9]")
a("_cols    = ['<r2>', '<ups2>', '<r ups>', '<r eta>', '<eta ups>', '<eta2>']")
a("_labels  = [")
a('    r"$\\langle r^2\\rangle$",')
a('    r"$\\langle \\upsilon^2\\rangle$",')
a('    r"$4\\langle r\\,\\upsilon\\rangle$",')
a('    r"$-\\tfrac{8}{3}\\langle r\\,\\eta\\rangle$",')
a('    r"$-\\tfrac{8}{3}\\langle\\eta\\,\\upsilon\\rangle$",')
a('    r"$\\tfrac{14}{9}\\langle\\eta^2\\rangle$",')
a("]")
a("_n_terms = len(_cols)")
a("")
a("# Weighted term columns")
a("for _i, (_c, _coef) in enumerate(zip(_cols, _coefs)):")
a("    _sub[f'_T{_i}'] = _coef * _sub[_c]")
a("_Tcols = [f'_T{i}' for i in range(_n_terms)]")
a("")
a("# Sum inside the square root: S = sum(T_k)")
a("_sub['_S'] = _sub[_Tcols].sum(axis=1)")
a("")
a("# LV for labels")
a("_sigma_to_LV = summary.groupby('sigma')['LV'].median().to_dict()")
a("")
a("# " + "=" * 76)
a("# 1. Covariance-based variance attribution")
a("# " + "=" * 76)
a("_fv_levels = sorted(_sub['fV'].dropna().unique())")
a("_attrib_rows = []")
a("")
a("for _fv in _fv_levels:")
a("    _g = _sub.loc[_sub['fV'] == _fv]")
a("    if _g.shape[0] < 3:")
a("        continue")
a("    _S = _g['_S'].to_numpy()")
a("    _var_S = np.var(_S, ddof=1)")
a("    if _var_S < 1e-15:")
a("        continue")
a("    _fracs = []")
a("    for _tc in _Tcols:")
a("        _cov = np.cov(_g[_tc].to_numpy(), _S)[0, 1]")
a("        _fracs.append(_cov / _var_S)")
a("    _attrib_rows.append([_fv] + _fracs)")
a("")
a("_attrib = pd.DataFrame(_attrib_rows, columns=['fV'] + _labels)")
a("_mean_attrib = _attrib[_labels].mean()")
a("")
a('print("--- Covariance attribution (% of across-sigma variance in S) ---")')
a('print("  averaged over fV levels:\\n")')
a("for _lab, _val in zip(_labels, _mean_attrib):")
a('    print(f"  {_lab:40s}  {_val:+6.1%}")')
a("print(f\"\\n  {'Sum':40s}  {_mean_attrib.sum():+6.1%}\")")
a("")
a("# -- Figure: stacked bar chart per fV + average --")
a("_plot_df = _attrib.copy()")
a("_avg_row = pd.DataFrame([['avg'] + _mean_attrib.tolist()], columns=['fV'] + _labels)")
a("_plot_df = pd.concat([_plot_df, _avg_row], ignore_index=True)")
a("")
a("_x = np.arange(len(_plot_df))")
a("_bar_colors = ['#2ca02c', '#1f77b4', '#ff7f0e', '#d62728', '#9467bd', '#8c564b']")
a("")
a("fig_attr, ax_attr = plt.subplots(figsize=(10, 4))")
a("_bot_pos = np.zeros(len(_x))")
a("_bot_neg = np.zeros(len(_x))")
a("for _k, _lab in enumerate(_labels):")
a("    _vals = _plot_df[_lab].to_numpy(float)")
a("    _pos = np.where(_vals >= 0, _vals, 0)")
a("    _neg = np.where(_vals < 0, _vals, 0)")
a("    ax_attr.bar(_x, _pos, bottom=_bot_pos, color=_bar_colors[_k], label=_lab,")
a("                width=0.7, edgecolor='w', linewidth=0.3)")
a("    ax_attr.bar(_x, _neg, bottom=_bot_neg, color=_bar_colors[_k],")
a("                width=0.7, edgecolor='w', linewidth=0.3)")
a("    _bot_pos += _pos")
a("    _bot_neg += _neg")
a("")
a("_xlabels = [f'{v:g}' if isinstance(v, float) else v for v in _plot_df['fV']]")
a("ax_attr.set_xticks(_x)")
a("ax_attr.set_xticklabels(_xlabels, fontsize=FS_TICK)")
a("ax_attr.axhline(1, color='k', ls=':', lw=0.6)")
a("ax_attr.axhline(0, color='k', ls='-', lw=0.5)")
a("ax_attr.axvline(len(_x) - 1.5, color='grey', ls='--', lw=0.8)")
a("ax_attr.set_xlabel(r'$f_V$', fontsize=FS_LABEL)")
a("ax_attr.set_ylabel('fraction of Var$(S)$', fontsize=FS_LABEL)")
a("ax_attr.set_title('Covariance attribution of length-scale variance', fontsize=FS_TITLE)")
a("ax_attr.legend(fontsize=FS_LEG - 1, ncol=3, loc='upper left', frameon=True)")
a("ax_attr.tick_params(labelsize=FS_TICK)")
a("fig_attr.tight_layout()")
a("plt.show()")
a("")
a("# " + "=" * 76)
a("# 2. Slope decomposition -- dT_k / d(LV) with fV fixed effects")
a("# " + "=" * 76)
a("import statsmodels.api as sm")
a("")
a("_sub['_LV'] = _sub['sigma'].map(_sigma_to_LV)")
a("_fv_dummies = pd.get_dummies(_sub['fV'], prefix='fV', drop_first=True, dtype=float)")
a("_X_base = sm.add_constant(pd.concat([_sub[['_LV']], _fv_dummies], axis=1))")
a("")
a("_slopes = {}")
a("_slopes_se = {}")
a("for _k, _lab in enumerate(_labels):")
a("    _y = _sub[_Tcols[_k]].to_numpy()")
a("    _fit = sm.OLS(_y, _X_base).fit()")
a("    _slopes[_lab] = _fit.params['_LV']")
a("    _slopes_se[_lab] = _fit.bse['_LV']")
a("")
a("# Also fit total S")
a("_fit_S = sm.OLS(_sub['_S'].to_numpy(), _X_base).fit()")
a("_slope_S = _fit_S.params['_LV']")
a("")
a('print("\\n--- Slope decomposition: dT_k / dLV (fV fixed effects) ---\\n")')
a("for _lab in _labels:")
a("    _s = _slopes[_lab]")
a("    _se = _slopes_se[_lab]")
a('    print(f"  {_lab:40s}  {_s:+.4f}  (+/-{_se:.4f})")')
a("print(f\"\\n  {'Sum of term slopes':40s}  {sum(_slopes.values()):+.4f}\")")
a("print(f\"  {'Total S slope':40s}  {_slope_S:+.4f}\")")
a("")
a("# -- Figure: grouped bar of slopes --")
a("fig_slope, ax_slope = plt.subplots(figsize=(8, 4))")
a("_sx = np.arange(_n_terms)")
a("_slope_vals = [_slopes[_lab] for _lab in _labels]")
a("_slope_ses  = [_slopes_se[_lab] for _lab in _labels]")
a("ax_slope.bar(_sx, _slope_vals, color=_bar_colors, width=0.6,")
a("             edgecolor='k', linewidth=0.4)")
a("ax_slope.errorbar(_sx, _slope_vals, yerr=_slope_ses, fmt='none',")
a("                  ecolor='k', capsize=3, lw=1)")
a("ax_slope.axhline(0, color='k', lw=0.5)")
a("ax_slope.axhline(_slope_S, color='grey', ls='--', lw=1,")
a("                 label=rf'total $\\partial S/\\partial L_V = {_slope_S:.4f}$')")
a("ax_slope.set_xticks(_sx)")
a("ax_slope.set_xticklabels(_labels, fontsize=FS_TICK - 1)")
a("ax_slope.set_ylabel(r'$\\partial T_k\\,/\\,\\partial L_V$  (m$^{-1}$)', fontsize=FS_LABEL)")
a("ax_slope.set_title(r'Sensitivity of each term to patch scale $L_V$ (fV fixed effects)',")
a("                   fontsize=FS_TITLE)")
a("ax_slope.legend(fontsize=FS_LEG, frameon=True)")
a("ax_slope.tick_params(labelsize=FS_TICK)")
a("fig_slope.tight_layout()")
a("plt.show()")
a("")
a("# " + "=" * 76)
a("# 3. Conditional profiles -- E[T_k | sigma] across patch scales")
a("# " + "=" * 76)
a("_sigma_levels = sorted(_sub['sigma'].dropna().unique())")
a("_lv_vals = [_sigma_to_LV.get(s, s) for s in _sigma_levels]")
a("")
a("_profiles = {}")
a("for _k, _lab in enumerate(_labels):")
a("    _means = []")
a("    for _s in _sigma_levels:")
a("        _means.append(_sub.loc[_sub['sigma'] == _s, _Tcols[_k]].mean())")
a("    _profiles[_lab] = _means")
a("")
a("fig_prof, ax_prof = plt.subplots(figsize=(7, 4.5))")
a("for _k, _lab in enumerate(_labels):")
a("    ax_prof.plot(_lv_vals, _profiles[_lab], 'o-', color=_bar_colors[_k],")
a("                 label=_lab, markersize=5, lw=1.5)")
a("ax_prof.axhline(0, color='k', ls='-', lw=0.5)")
a("ax_prof.set_xlabel(r'$L_V$ (m)', fontsize=FS_LABEL)")
a("ax_prof.set_ylabel('mean term value', fontsize=FS_LABEL)")
a("ax_prof.set_title(r'Conditional mean of each $S_f$ term vs patch scale',")
a("                  fontsize=FS_TITLE)")
a("ax_prof.legend(fontsize=FS_LEG - 1, frameon=True)")
a("ax_prof.tick_params(labelsize=FS_TICK)")
a("fig_prof.tight_layout()")
a("plt.show()")
a("")
a("# -- Save all three to scratch --")
a("_, _scratch, _ = _fig_dirs()")
a("fig_attr.savefig(_os.path.join(_scratch, 'lengthscale_cov_attribution.png'),")
a("                 dpi=200, bbox_inches='tight')")
a("fig_slope.savefig(_os.path.join(_scratch, 'lengthscale_slope_decomp.png'),")
a("                  dpi=200, bbox_inches='tight')")
a("fig_prof.savefig(_os.path.join(_scratch, 'lengthscale_conditional_profiles.png'),")
a("                 dpi=200, bbox_inches='tight')")
a('print("\\nSaved 3 figures to scratch/")')

nb["cells"][target_idx]["source"] = [line + "\n" for line in L]

with open(NB, "w") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)
    f.write("\n")
print("Fixed cell source. Done.")
